<?php
if( function_exists('acf_add_local_field_group') ):


  acf_add_local_field_group( array(
    'key' => 'group_a4hsiuaj',
    'title' => 'Intro Text',
    'fields' => array(
      array(
        'key' => 'field_654a9957b8e3d',
        'label' => 'Text',
        'name' => 'text',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_654a9961b8e3e',
        'label' => 'CTA <span class="opt">optional</span>',
        'name' => 'cta',
        'aria-label' => '',
        'type' => 'link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
      ),
      array(
        'key' => 'field_654a996bb8e3f',
        'label' => 'Image',
        'name' => 'image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_2vl09ey50',
        'label' => 'Image Type',
        'name' => 'image_type',
        'aria-label' => '',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'card' => 'Card',
          'full' => 'Full',
        ),
        'default_value' => 'card',
        'return_format' => 'value',
        'allow_null' => 0,
        'other_choice' => 0,
        'layout' => 'horizontal',
        'save_other_choice' => 0,
      ),
      array(
        'key' => 'field_654cea06baf36',
        'label' => 'Style',
        'name' => 'style',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => 'Background color, text color, etc.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'brown' => 'Brown',
          'light-green' => 'Light Green',
          'dark-green' => 'Dark Green',
        ),
        'default_value' => 'brown',
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
      ),
      // array(
      // 	'key' => 'field_c329gudlm',
      // 	'label' => 'Additional Fields',
      // 	'name' => '',
      // 	'type' => 'accordion',
      // 	'instructions' => '',
      // 	'required' => 0,
      // 	'conditional_logic' => 0,
      // 	'wrapper' => array(
      // 		'width' => '',
      // 		'class' => '',
      // 		'id' => '',
      // 	),
      // 	'open' => 0,
      // 	'multi_expand' => 0,
      // 	'endpoint' => 0,
      // ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/colorblock',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ) );

endif;
