<?php
if( function_exists('acf_add_local_field_group') ):


  acf_add_local_field_group( array(
    'key' => 'group_w4ezudybd',
    'title' => 'Carousel',
    'fields' => array(
      array(
        'key' => 'field_654bf604717fa',
        'label' => 'Slides',
        'name' => 'slides',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'row',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Row',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_654bf609717fb',
            'label' => 'Image',
            'name' => 'image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'thumbnail',
            'parent_repeater' => 'field_654bf604717fa',
          ),
          array(
            'key' => 'field_654bf618717fc',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_654bf604717fa',
          ),
          array(
            'key' => 'field_654bf621717fd',
            'label' => 'Text',
            'name' => 'text',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => '',
            'placeholder' => '',
            'new_lines' => 'br',
            'parent_repeater' => 'field_654bf604717fa',
          ),
        ),
      ),
      // array(
      // 	'key' => 'field_c329gudlm',
      // 	'label' => 'Additional Fields',
      // 	'name' => '',
      // 	'type' => 'accordion',
      // 	'instructions' => '',
      // 	'required' => 0,
      // 	'conditional_logic' => 0,
      // 	'wrapper' => array(
      // 		'width' => '',
      // 		'class' => '',
      // 		'id' => '',
      // 	),
      // 	'open' => 0,
      // 	'multi_expand' => 0,
      // 	'endpoint' => 0,
      // ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/' . $args['name'],
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ) );

endif;
