<?php
$manual_version_update = ! empty( $_GET['manual-update'] ) && $_GET['manual-update'] == 1;
acf_add_local_field_group(array (
	'key' => 'group_ujzbd67g',
	'title' => 'Recaptcha',
	'fields' => array (
    array(
      'key' => 'field_5f7f2338fb1f5',
      'label' => 'Recaptcha Keys',
      'name' => 'recaptcha_keys',
      'type' => 'group',
      'instructions' => '<a href="https://www.google.com/recaptcha/admin" target="_blank">Manage Google Recaptcha Keys</a>.  Leave empty if do not want to use Recaptcha.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'block',
      'sub_fields' => array(
        array(
          'key' => 'field_5f7f2349fb1f6',
          'label' => 'Site Key',
          'name' => 'site_key',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5f7f2350fb1f7',
          'label' => 'Secret Key',
          'name' => 'secret_key',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_fdfcf7d59fe1a',
          'label' => 'Score',
          'name' => 'score',
          'type' => 'text',
          'instructions' => 'Must be a number between 0.0 and 1.0.  Google Recaptcha returns a score (1.0 = most likely human & 0.0 = most likely a bot).  Default score to register as valid is 0.5.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '0.5',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
    ),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-recaptcha',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));
